apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah-unprivileged
spec:
  params:
    - name: IMAGE
      description: Reference of the image buildah will produce
    - name: BUILDER_IMAGE
      description: The location of the buildah builder image
      default: quay.io/buildah/stable:v1.27.0
    - name: STORAGE_DRIVER
      description: Set buildah storage driver
      default: vfs
    - name: DOCKERFILE
      description: Path to the Dockerfile to build
      default: ./Dockerfile
    - name: CONTEXT
      description: Path to the directory to use as context
      default: .
    - name: TLSVERIFY
      description: Verify the TLS on the registry endpoint
      type: string
      default: "true"
    - name: FORMAT
      description: The format of the built container, oci or docker
      default: "docker"
    - name: BUILD_EXTRA_ARGS
      description: Extra parameters passed for the build command
      default: ""
    - name: PUSH_EXTRA_ARGS
      description: Extra parameters passed for the push command
      default: ""
    - name: SKIP_PUSH
      description: Skip pushing the built image
      default: "false"
  workspaces:
    - name: source
  results:
    - name: IMAGE_DIGEST
      description: Digest of the image just built
    - name: IMAGE_URL
      description: Image repository where the built image was pushed
  steps:
    - name: build-and-push
      image: $(params.BUILDER_IMAGE)
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env bash
        set -e
        
        echo "Building image $(params.IMAGE)"
        
        buildah --storage-driver=$(params.STORAGE_DRIVER) bud \
          $(params.BUILD_EXTRA_ARGS) \
          --format=$(params.FORMAT) \
          --tls-verify=$(params.TLSVERIFY) \
          --no-cache \
          -f $(params.DOCKERFILE) \
          -t $(params.IMAGE) \
          $(params.CONTEXT)
        
        if [ "$(params.SKIP_PUSH)" = "false" ]; then
          echo "Pushing image $(params.IMAGE)"
          buildah --storage-driver=$(params.STORAGE_DRIVER) push \
            $(params.PUSH_EXTRA_ARGS) \
            --tls-verify=$(params.TLSVERIFY) \
            --digestfile /tmp/image-digest \
            $(params.IMAGE) \
            docker://$(params.IMAGE)
          
          cat /tmp/image-digest | tee $(results.IMAGE_DIGEST.path)
          echo -n "$(params.IMAGE)" | tee $(results.IMAGE_URL.path)
        else
          echo "Skipping push as requested"
          echo -n "" | tee $(results.IMAGE_DIGEST.path)
          echo -n "$(params.IMAGE)" | tee $(results.IMAGE_URL.path)
        fi
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        capabilities:
          add:
            - SETFCAP
      volumeMounts:
        - name: varlibcontainers
          mountPath: /home/build/.local/share/containers
  volumes:
    - name: varlibcontainers
      emptyDir: {}
