apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  workspaces:
    - name: output
  params:
    - name: repo-url
      type: string
    - name: branch
      type: string
      default: "main"  # Updated from master to main
    - name: build-image
      type: string
  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: output

    - name: clone
      taskRef:
        name: git-clone
      runAfter:
        - cleanup
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)
      workspaces:
        - name: output
          workspace: output

    - name: lint
      taskRef:
        name: flake8
      runAfter:
        - clone
      workspaces:
        - name: source
          workspace: output

    - name: tests
      taskRef:
        name: nose
      runAfter:
        - lint
      workspaces:
        - name: source
          workspace: output

    - name: build
      taskRef:
        name: buildah
      runAfter:
        - tests
      params:
        - name: IMAGE
          value: $(params.build-image)
      workspaces:
        - name: source
          workspace: output

  finally:
    - name: deploy
      taskRef:
        name: openshift-client
      params:
        - name: SCRIPT
          value: |
            # Check if deployment exists. If not, create it. If yes, restart it.
            if ! oc get deployment ny-restaurants > /dev/null 2>&1; then
              echo "Creating new deployment..."
              oc create deployment ny-restaurants --image=$(params.build-image)
              oc expose deployment ny-restaurants --port=8080
              oc expose service ny-restaurants
            else
              echo "Updating existing deployment..."
              oc rollout restart deployment/ny-restaurants
            fi
            oc get route ny-restaurants
      workspaces:
        - name: manifest-dir
          workspace: output